// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUX8hWuXk-SDN-rfl9KN4cK-GHd_7XK6o',
    appId: '1:116772309492:web:ba32049fd77cbbfd7691a1',
    messagingSenderId: '116772309492',
    projectId: 'neonoverflow-8091c',
    authDomain: 'neonoverflow-8091c.firebaseapp.com',
    storageBucket: 'neonoverflow-8091c.appspot.com',
    measurementId: 'G-Q4HQ1L3TZB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl4S6XywblTY3eDYGChuA1Eequej-3BIQ',
    appId: '1:116772309492:android:5349f32ff39c591b7691a1',
    messagingSenderId: '116772309492',
    projectId: 'neonoverflow-8091c',
    storageBucket: 'neonoverflow-8091c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdJl8zui-fhIdKEFfU-IfO02P2Q4CSV4s',
    appId: '1:116772309492:ios:407c24dcececbe487691a1',
    messagingSenderId: '116772309492',
    projectId: 'neonoverflow-8091c',
    storageBucket: 'neonoverflow-8091c.appspot.com',
    iosClientId: '116772309492-ekmevu6doe10l3hcj0e29a4upvo52cf3.apps.googleusercontent.com',
    iosBundleId: 'com.example.neonoverflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdJl8zui-fhIdKEFfU-IfO02P2Q4CSV4s',
    appId: '1:116772309492:ios:d4748df08ac5f7c77691a1',
    messagingSenderId: '116772309492',
    projectId: 'neonoverflow-8091c',
    storageBucket: 'neonoverflow-8091c.appspot.com',
    iosClientId: '116772309492-pn74tg3odqj821v13ontj8vk7qv2q8cv.apps.googleusercontent.com',
    iosBundleId: 'com.example.neonoverflow.RunnerTests',
  );
}
